# Generated by Django 3.1.11 on 2021-06-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210601_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='event',
        ),
    ]
