# Generated by Django 3.1.11 on 2021-06-01 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_comment_profile'),
        ('support', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='support',
            field=models.ManyToManyField(to='support.MessageToSupport'),
        ),
    ]
