# Generated by Django 3.1.11 on 2021-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_image', to='posts.Post'),
        ),
    ]
