# Generated by Django 3.1.11 on 2021-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        ('images', '0002_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='support_image', to='support.MessageToSupport'),
        ),
    ]
