# Generated by Django 3.1.11 on 2021-06-01 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_comment_profile'),
        ('support', '0001_initial'),
        ('images', '0003_auto_20210601_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ManyToManyField(blank=True, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='support',
            field=models.ManyToManyField(blank=True, to='support.MessageToSupport'),
        ),
    ]
