# Generated by Django 3.1.11 on 2021-06-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_profile'),
        ('support', '0001_initial'),
        ('images', '0004_auto_20210601_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_image', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='support_image', to='support.MessageToSupport'),
        ),
    ]
