# Generated by Django 3.1.11 on 2021-06-02 08:15

from django.db import migrations, models
import images.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210602_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to=images.utilities.get_timestamp_path, verbose_name='изображение', width_field=100),
        ),
    ]
