# Generated by Django 3.1.11 on 2021-06-02 11:14

from django.db import migrations, models
import images.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('images', '0006_auto_20210602_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_image', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=images.utilities.get_timestamp_path, verbose_name='изображение'),
        ),
    ]
