# Generated by Django 3.1.11 on 2021-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('images', '0007_auto_20210602_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='event_image', to='events.Event'),
        ),
    ]
