# Generated by Django 3.1.11 on 2021-06-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20210602_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='event',
        ),
    ]
