# Generated by Django 3.2.3 on 2021-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_exp',
            field=models.SmallIntegerField(),
        ),
    ]
