# Generated by Django 3.2.3 on 2021-05-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
        ('posts', '0004_alter_profile_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
