# Generated by Django 3.2.3 on 2021-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=250, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок поста'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.SmallIntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='knowledge',
            field=models.TextField(max_length=3000, verbose_name='знания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_exp',
            field=models.SmallIntegerField(verbose_name='опыт работы'),
        ),
    ]
