# Generated by Django 3.1.11 on 2021-06-18 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('images', '0002_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='event',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.office', verbose_name='офис'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.ManyToManyField(blank=True, related_name='eventsgroups', through='events.EventGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
