# Generated by Django 3.2.3 on 2021-05-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'События'},
        ),
    ]
